### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by lestoni** [C4AProjects/Flex-Topup#3]
hey @maxosba do we have a lead tech for this project?

**Comment by maxosba** [comment]
It is Adams

Regards
Amadou Daffe

**Comment by lestoni** [comment]
@JohnAdamsy i hope you have seen the API documentation @maxosba added to the activeCollab, let me know when you go through it we compare notes.

Cheers

**Comment by JohnAdamsy** [comment]
@lestoni Yes indeed

**Comment by JohnAdamsy** [comment]
I feared it was ......and then it turned out to be....XML!! :scream_cat:  lol

**Comment by saladthieves** [comment]
@JohnAdamsy I know the feeling. I got a heart attack when I discovered that it was just a PDF file :joy: ...then I died when I got to the part that talks about how to communicate with the API...looked for json and found nothing!
